name: TitleRedactedCalc
options:
  bundleIdPrefix: com.titleRedactedCalc
  deploymentTarget: "14.0"
  xcodeGen: true

targets:
  CoreCalculator:
    type: framework
    platform: macOS
    sources: [Sources/CoreCalculator]
    settings:
      base:
        SWIFT_VERSION: "6.0"
        GENERATE_INFOPLIST_FILE: YES

  Utilities:
    type: framework
    platform: macOS
    sources: [Sources/Utilities]
    settings:
      base:
        SWIFT_VERSION: "6.0"
        GENERATE_INFOPLIST_FILE: YES

  ViewModels:
    type: framework
    platform: macOS
    sources: [Sources/ViewModels]
    dependencies:
      - target: CoreCalculator
      - target: Utilities
    settings:
      base:
        SWIFT_VERSION: "6.0"
        GENERATE_INFOPLIST_FILE: YES

  TitleRedactedCalcApp:
    type: application
    platform: macOS
    sources: [Sources/swift-calc]
    dependencies:
      - target: ViewModels
      - target: CoreCalculator
      - target: Utilities
    settings:
      base:
        SWIFT_VERSION: "6.0"
        INFOPLIST_KEY_NSPrincipalClass: NSApplication
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: TitleRedactedCalc
        CURRENT_PROJECT_VERSION: "1"
        MARKETING_VERSION: "1.0.0"

  CalculatorTests:
    type: bundle.unit-test
    platform: macOS
    sources: [Tests/CalculatorTests]
    dependencies:
      - target: CoreCalculator
      - target: ViewModels
      - target: Utilities
    settings:
      base:
        SWIFT_VERSION: "6.0"
        GENERATE_INFOPLIST_FILE: YES
